name: Hello world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: echo "this is line" 
 test:
   run-on: ubuntu-latest
   steps: 
     - name: My common steps
       run: echo "run the test one"
            echo "hello my git"
        
      
        
