# Scalars
name: prathyusha
location: Bangalore
Profession: no job

# List
Hobbies:
  - Reading
  - Writing
  - Practice

# Mapping
Favoritecolour:
  colour1: blue
  colour2: green
  colour3: Red

Playinggames:
  game1: hockey
  game2: ball

# Multiline scalar
whatisthisiamlearn: |
  I am learning scalars.
  I am learning lists.
  I am learning mappings.
  I am learning multiline scalars.
  All are scalars, lists, mappings and multiline.
